/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    XIVCard: typeof import('./components/XIVCard.vue')['default']
    XIVItem: typeof import('./components/Item/XIVItem.vue')['default']
    XIVItems: typeof import('./components/Item/XIVItems.vue')['default']
    XIVItemTitle: typeof import('./components/Item/XIVItemTitle.vue')['default']
  }
}
