import { XIVGamePatch } from './XIVGamePatch'

export interface XIVBaseParam {
  BaseParam?: any
  BaseParamTarget: string
  BaseParamTargetID: number
}

export interface XIVDescriptionJSON {
  DescriptionJSON: string[]
  DescriptionJSON_chs?: string[]
  DescriptionJSON_de?: string[]
  DescriptionJSON_en?: string[]
  DescriptionJSON_fr?: string[]
  DescriptionJSON_ja?: string[]
  DescriptionJSON_kr?: string[]
}

export interface XIVGameContentLink {
  Item?: number[]
  Item0?: number[]
  Item1?: number[]
  Item3?: number[]
  ItemCatalyst0?: number[]
  ItemCatalyst1?: number[]
  ItemIngredient8?: number[]
  ItemIngredient9?: number[]
  ItemReceive40?: number[]
}

export interface XIVGameContentLinks {
  GardeningSeed?: XIVGameContentLink
  GatheringItem?: XIVGameContentLink
  LeveRewardItemGroup?: XIVGameContentLink
  Quest?: XIVGameContentLink
  Recipe?: XIVGameContentLink
  RetainerTaskNormal?: XIVGameContentLink
  SpecialShop?: XIVGameContentLink
}

export interface XIVItemUICategory {
  ID: number
  Icon: string
  IconHD: string
  IconID: number
  Name: string
  Name_chs: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
  OrderMajor?: number
  OrderMinor?: number
}

export interface XIVItemData {
  AdditionalData: number
  Adjective: number
  AetherialReduce: number
  AlwaysCollectable: number
  Article: number
  BaseParam0: XIVBaseParam
  BaseParam1: XIVBaseParam
  BaseParam2: XIVBaseParam
  BaseParam3: XIVBaseParam
  BaseParam4: XIVBaseParam
  BaseParam5: XIVBaseParam
  BaseParamModifier: number
  BaseParamSpecial0: XIVBaseParam
  BaseParamSpecial1: XIVBaseParam
  BaseParamSpecial2: XIVBaseParam
  BaseParamSpecial3: XIVBaseParam
  BaseParamSpecial4: XIVBaseParam
  BaseParamSpecial5: XIVBaseParam
  BaseParamValue0: number
  BaseParamValue1: number
  BaseParamValue2: number
  BaseParamValue3: number
  BaseParamValue4: number
  BaseParamValue5: number
  BaseParamValueSpecial0: number
  BaseParamValueSpecial1: number
  BaseParamValueSpecial2: number
  BaseParamValueSpecial3: number
  BaseParamValueSpecial4: number
  BaseParamValueSpecial5: number
  Block: number
  BlockRate: number
  CanBeHq: number
  CastTimeS: number
  ClassJobCategory?: any
  ClassJobCategoryTarget: string
  ClassJobCategoryTargetID: number
  ClassJobRepair?: any
  ClassJobRepairTarget: string
  ClassJobRepairTargetID: number
  ClassJobUse?: any
  ClassJobUseTarget: string
  ClassJobUseTargetID: number
  CooldownS: number
  DamageMag: number
  DamagePhys: number
  DefenseMag: number
  DefensePhys: number
  DelayMs: number
  Description: string
  Description_chs: string
  Description_de: string
  Description_en: string
  Description_fr: string
  Description_ja: string
  Description_kr?: string
  Desynth: number
  EquipRestriction: number
  EquipSlotCategory?: any
  EquipSlotCategoryTarget: string
  EquipSlotCategoryTargetID: number
  FilterGroup: number
  GameContentLinks: XIVGameContentLinks
  GamePatch: XIVGamePatch
  GrandCompany?: any
  GrandCompanyTarget: string
  GrandCompanyTargetID: number
  ID: number
  Icon: string
  IconHD: string
  IconID: number
  IsAdvancedMeldingPermitted: number
  IsCollectable: number
  IsCrestWorthy: number
  IsDyeable: number
  IsGlamourous: number
  IsIndisposable: number
  IsPvP: number
  IsUnique: number
  IsUntradable: number
  ItemAction?: any
  ItemActionTarget: string
  ItemActionTargetID: number
  ItemGlamour?: any
  ItemGlamourTarget: string
  ItemGlamourTargetID: number
  ItemKind: any
  ItemRepair?: any
  ItemRepairTarget: string
  ItemRepairTargetID: number
  ItemSearchCategory: XIVItemUICategory
  ItemSearchCategoryTarget: string
  ItemSearchCategoryTargetID: number
  ItemSeries?: any
  ItemSeriesTarget: string
  ItemSeriesTargetID: number
  ItemSortCategory: any
  ItemSortCategoryTarget: string
  ItemSortCategoryTargetID: number
  ItemSpecialBonus?: any
  ItemSpecialBonusParam: number
  ItemSpecialBonusTarget: string
  ItemSpecialBonusTargetID: number
  ItemUICategory: XIVItemUICategory
  ItemUICategoryTarget: string
  ItemUICategoryTargetID: number
  LevelEquip: number
  LevelItem: number
  Lot: number
  Materia?: any
  MateriaSlotCount: number
  MaterializeType: number
  ModelMain: string
  ModelSub: string
  Name: string
  Name_chs: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
  Patch: number
  Plural: string
  Plural_chs: string
  Plural_de: string
  Plural_en: string
  Plural_fr: string
  Plural_ja: string
  PossessivePronoun: number
  PriceLow: number
  PriceMid: number
  Pronoun: number
  Rarity: number
  Singular: string
  Singular_chs: string
  Singular_de: string
  Singular_en: string
  Singular_fr: string
  Singular_ja: string
  StackSize: number
  StartsWithVowel: number
  SubStatCategory: number
  Url: string
}
